### ISSUE TITLE
Android app fails to start after second run

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-mobile#12]
Tested on Samsung Galaxy S21

![image](https://user-images.githubusercontent.com/331478/128952331-14365a61-424e-4656-a5c9-d90f78b410a9.jpeg)

**Comment by Ravigon** [comment]
I too am experiencing this same issue. If I just close the app and try to reopen it, it will just have a spinning logo and won't open. In order to get around this I had to remove and reinstall the app. I find that if I log out from the menu first and then close the app, I can then reopen it and login and it works as it should (Need to log out via the menu every time though).

**Comment by curtishall** [comment]
Fixed in Build 4
